Repository andromedaprotocol/andromeda-core, pull requests merged in 2024-11, with the labels that each got.

#593 ci(Mergify): configuration update
  .github/mergify.yml
Labels: ci: skip-changelog

#594 fix: add cw20 missing receive schema
  CHANGELOG.md
  contracts/fungible-tokens/andromeda-cw20-staking/examples/schema.rs
  contracts/fungible-tokens/andromeda-lockdrop/examples/schema.rs
  contracts/non-fungible-tokens/andromeda-crowdfund/examples/schema.rs
  contracts/non-fungible-tokens/andromeda-marketplace/examples/schema.rs
  contracts/os/andromeda-economics/examples/schema.rs
Labels: ci: skip-changelog, backport/v1.1.x

#589 feat: Marketplace & Auction Adjustments
  CHANGELOG.md
  Cargo.lock
  contracts/non-fungible-tokens/andromeda-auction/Cargo.toml
  contracts/non-fungible-tokens/andromeda-auction/src/contract.rs
  contracts/non-fungible-tokens/andromeda-auction/src/mock.rs
  contracts/non-fungible-tokens/andromeda-auction/src/testing/tests.rs
  contracts/non-fungible-tokens/andromeda-marketplace/Cargo.toml
  contracts/non-fungible-tokens/andromeda-marketplace/src/contract.rs
  contracts/non-fungible-tokens/andromeda-marketplace/src/testing/tests.rs
  packages/andromeda-non-fungible-tokens/src/auction.rs
  packages/andromeda-non-fungible-tokens/src/marketplace.rs
  packages/std/src/common/denom.rs
  packages/std/src/error.rs
  tests-integration/tests/auction_app.rs
Labels: backport/v1.1.x

#590 ref: Expiry in Crowdfund
  Cargo.lock
  contracts/non-fungible-tokens/andromeda-crowdfund/Cargo.toml
  contracts/non-fungible-tokens/andromeda-crowdfund/src/contract.rs
  contracts/non-fungible-tokens/andromeda-crowdfund/src/mock.rs
  contracts/non-fungible-tokens/andromeda-crowdfund/src/testing/tests.rs
  packages/andromeda-non-fungible-tokens/src/crowdfund.rs
  tests-integration/tests/crowdfund_app.rs
Labels: ci: skip-changelog, backport/v1.1.x

#600 build: beta tag prerelease contracts
  Cargo.lock
  contracts/ecosystem/andromeda-vault/Cargo.toml
  contracts/finance/andromeda-conditional-splitter/Cargo.toml
  contracts/finance/andromeda-cross-chain-swap/Cargo.toml
  contracts/finance/andromeda-rate-limiting-withdrawals/Cargo.toml
  contracts/finance/andromeda-set-amount-splitter/Cargo.toml
  contracts/finance/andromeda-validator-staking/Cargo.toml
  contracts/finance/andromeda-vesting/Cargo.toml
  contracts/finance/andromeda-weighted-distribution-splitter/Cargo.toml
  contracts/modules/andromeda-shunting/Cargo.toml
Labels: ci: skip-changelog

#601 ci: release workflow
  .github/workflows/release-artifacts.yml
  .github/workflows/release.yml
  .github/workflows/rust.yml
  .gitignore
  build_schema.sh
Labels: ci: skip-changelog, backport/v1.1.x

#592 chore: changelog for 1.1
  CHANGELOG.md
Labels: ci: skip-changelog

#606 build: added makefile
  .github/workflows/rust.yml
  Makefile
  scripts/build.sh
  scripts/build_all.sh
  scripts/build_schema.sh
  scripts/build_version_map.sh
  scripts/bump_version.sh
  scripts/install_binaryen.sh
Labels: ci: skip-changelog, backport/v1.1.x

#608 fix: update build_all.sh to append version after build
  scripts/build_all.sh
Labels: ci: skip-changelog, backport/v1.1.x

#610 fix: append version after build only if version is not present
  scripts/build_all.sh
Labels: ci: skip-changelog, backport/v1.1.x

#603 fix: amount sold incorrect for tiers with limits
  contracts/non-fungible-tokens/andromeda-crowdfund/src/mock.rs
  contracts/non-fungible-tokens/andromeda-crowdfund/src/state.rs
  tests-integration/tests/crowdfund_app.rs
Labels: ci: skip-changelog, backport/v1.1.x

#621 chore: version fixes
  Cargo.lock
  contracts/finance/andromeda-conditional-splitter/Cargo.toml
  contracts/finance/andromeda-rate-limiting-withdrawals/Cargo.toml
  contracts/finance/andromeda-set-amount-splitter/Cargo.toml
  contracts/finance/andromeda-vesting/Cargo.toml
  contracts/finance/andromeda-weighted-distribution-splitter/Cargo.toml
  contracts/non-fungible-tokens/andromeda-crowdfund/Cargo.toml
Labels: ci: skip-changelog

#625 ci: add dependabot.yml
  .github/dependabot.yml
Labels: ci: skip-changelog

#624 ci: git actions versions
  .github/workflows/deploy.yml
  .github/workflows/release.yml
Labels: ci: skip-changelog

#650 Version changed to 0.x.0-beta for undeployed contracts
  Cargo.lock
  contracts/data-storage/andromeda-boolean/Cargo.toml
  contracts/data-storage/andromeda-counter/Cargo.toml
  contracts/data-storage/andromeda-graph/Cargo.toml
  contracts/data-storage/andromeda-point/Cargo.toml
  contracts/data-storage/andromeda-string-storage/Cargo.toml
  contracts/finance/andromeda-fixed-multisig/Cargo.toml
  contracts/modules/andromeda-curve/Cargo.toml
  contracts/modules/andromeda-date-time/Cargo.toml
Labels: ci: skip-changelog

#651 test: fixed marketplace tests
  .cargo/config.toml
  .github/workflows/rust.yml
  Makefile
  contracts/app/andromeda-app-contract/Cargo.toml
  contracts/ecosystem/andromeda-vault/Cargo.toml
  contracts/non-fungible-tokens/andromeda-cw721/src/contract.rs
  contracts/non-fungible-tokens/andromeda-marketplace/Cargo.toml
  contracts/non-fungible-tokens/andromeda-marketplace/src/contract.rs
  contracts/non-fungible-tokens/andromeda-marketplace/src/mock.rs
  contracts/os/andromeda-kernel/src/contract.rs
  contracts/os/andromeda-kernel/src/execute.rs
  packages/andromeda-app/Cargo.toml
  packages/andromeda-finance/src/validator_staking.rs
  packages/andromeda-fungible-tokens/src/cw20.rs
  packages/andromeda-non-fungible-tokens/src/auction.rs
  packages/andromeda-non-fungible-tokens/src/crowdfund.rs
  packages/andromeda-non-fungible-tokens/src/marketplace.rs
  packages/std/src/ado_contract/app.rs
  packages/std/src/os/adodb.rs
  packages/std/src/os/ibc_registry.rs
  packages/std/src/os/kernel.rs
  packages/std/src/os/vfs.rs
  tests-integration/Cargo.toml
  tests-integration/tests/app.rs
  tests-integration/tests/auction_app.rs
  tests-integration/tests/cw20_app.rs
  tests-integration/tests/kernel_orch.rs
  tests-integration/tests/marketplace_app.rs
  tests-integration/tests/mod.rs
  tests-integration/tests/primitive.rs
  tests-integration/tests/set_amount_splitter.rs
  tests-integration/tests/validator_staking.rs
Labels: ci: skip-changelog

#605 ci: changes to contract builds
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/release.yml
  .github/workflows/rust.yml
  Makefile
  packages/std/src/ado_contract/app.rs
Labels: ci: skip-changelog, ci: skip-build

#663 Functionality Update of Curve ADO
  Cargo.lock
  contracts/modules/andromeda-curve/Cargo.toml
  contracts/modules/andromeda-curve/src/contract.rs
  contracts/modules/andromeda-curve/src/mock.rs
  contracts/modules/andromeda-curve/src/state.rs
  contracts/modules/andromeda-curve/src/testing/mock.rs
  contracts/modules/andromeda-curve/src/testing/tests.rs
  packages/andromeda-modules/src/curve.rs
Labels: ci: skip-changelog

#674 ref: rename release_unit to release_duration
  Cargo.lock
  contracts/finance/andromeda-vesting/Cargo.toml
  contracts/finance/andromeda-vesting/src/contract.rs
  contracts/finance/andromeda-vesting/src/state.rs
  contracts/finance/andromeda-vesting/src/testing/tests.rs
  packages/andromeda-finance/src/vesting.rs
Labels: ci: skip-changelog

#676 Release 3 Changelog and Backport tags
  .github/mergify.yml
  CHANGELOG.md
  Cargo.lock
  contracts/finance/andromeda-validator-staking/Cargo.toml
  contracts/finance/andromeda-vesting/Cargo.toml
Labels: ci: skip-changelog, ci: skip-build
