Repository andromedaprotocol/andromeda-core, pull requests merged in 2024-12, with the labels that each got.

#677 Trigger tests
  .github/workflows/deploy.yml
Labels: ci: skip-changelog

#685 feat: add attributes to add_child in vfs
  Cargo.lock
  contracts/os/andromeda-vfs/Cargo.toml
  contracts/os/andromeda-vfs/src/execute.rs
Labels: ci: skip-changelog

#689 feat: added mainnet chain configs
  .github/workflows/release.yml
  contracts/os/andromeda-kernel/src/interface.rs
  packages/deploy/src/chains/mainnets.rs
  packages/deploy/src/chains/mod.rs
  packages/deploy/src/chains/testnets.rs
  packages/deploy/src/contracts.rs
  packages/deploy/src/os.rs
Labels: ci: skip-changelog, ci: skip-build, backport/release/3

#691 build: updated validator staking version
  Cargo.lock
  contracts/finance/andromeda-validator-staking/Cargo.toml
Labels: ci: skip-changelog, ci: skip-build, backport/release/3

#693 ci: release script changes
  .github/workflows/release.yml
  packages/deploy/src/chains/mainnets.rs
  scripts/build_all.sh
Labels: ci: skip-changelog, ci: skip-build, backport/release/3

#701 Changes to CI
  .github/workflows/deploy.yml
Labels: ci: skip-changelog, ci: skip-build

#702 add: added osmosis testnet info to testnets.rs
  packages/deploy/src/chains/testnets.rs
Labels: ci: skip-changelog, ci: skip-build

#705 ci: add nightly release schedule
  .github/workflows/nightly.yml
Labels: ci: skip-changelog, ci: skip-build

#712 fix: rename references to development to main
  .github/mergify.yml
  .github/workflows/build.yml
  .github/workflows/changelog.yml
  .github/workflows/rust.yml
  README.md
Labels: ci: skip-changelog

#714 Moved Distance ADO to Andromeda-math
  Cargo.lock
  contracts/math/andromeda-distance/.cargo/config
  contracts/math/andromeda-distance/Cargo.toml
  contracts/math/andromeda-distance/examples/schema.rs
  contracts/math/andromeda-distance/src/contract.rs
  contracts/math/andromeda-distance/src/interface.rs
  contracts/math/andromeda-distance/src/lib.rs
  contracts/math/andromeda-distance/src/mock.rs
  contracts/math/andromeda-distance/src/testing/mock.rs
  contracts/math/andromeda-distance/src/testing/mod.rs
  contracts/math/andromeda-distance/src/testing/tests.rs
  contracts/modules/andromeda-distance/src/lib.rs
  contracts/non-fungible-tokens/andromeda-crowdfund/src/contract.rs
  contracts/non-fungible-tokens/andromeda-crowdfund/src/testing/tests.rs
  packages/andromeda-non-fungible-tokens/src/crowdfund.rs
  packages/deploy/Cargo.toml
  packages/deploy/src/contracts.rs
  packages/std/src/error.rs
Labels: ci: skip-changelog

#737 chore: remove unused deps using cargo-udeps
  Cargo.lock
  contracts/accounts/andromeda-fixed-multisig/Cargo.toml
  contracts/data-storage/andromeda-form/Cargo.toml
  contracts/os/andromeda-ibc-registry/Cargo.toml
  contracts/os/andromeda-kernel/Cargo.toml
  ibc-tests/Cargo.toml
  packages/andromeda-finance/Cargo.toml
  packages/andromeda-fungible-tokens/Cargo.toml
  packages/andromeda-testing-e2e/Cargo.toml
  packages/std/Cargo.toml
Labels: ci: skip-changelog
