Repository andromedaprotocol/andromeda-core, pull requests merged in 2025-01, with the labels that each got.

#700 Bump version
  Cargo.lock
  contracts/accounts/andromeda-fixed-multisig/Cargo.toml
  contracts/data-storage/andromeda-boolean/Cargo.toml
  contracts/data-storage/andromeda-form/Cargo.toml
  contracts/data-storage/andromeda-string-storage/Cargo.toml
  contracts/math/andromeda-counter/Cargo.toml
  contracts/math/andromeda-curve/Cargo.toml
  contracts/math/andromeda-date-time/Cargo.toml
  contracts/math/andromeda-graph/Cargo.toml
  contracts/math/andromeda-graph/src/contract.rs
  contracts/math/andromeda-graph/src/interface.rs
  contracts/math/andromeda-graph/src/lib.rs
  contracts/math/andromeda-matrix/Cargo.toml
  contracts/math/andromeda-point/Cargo.toml
  contracts/math/andromeda-point/src/contract.rs
  contracts/math/andromeda-point/src/interface.rs
  contracts/math/andromeda-point/src/lib.rs
  contracts/math/andromeda-shunting/Cargo.toml
  contracts/modules/andromeda-schema/Cargo.toml
  packages/deploy/Cargo.toml
  packages/deploy/src/contracts.rs
Labels: ci: skip-changelog

#763 ci: backport tags for release 4
  .github/mergify.yml
Labels: ci: skip-changelog, ci: skip-build

#762 Update Curve ADO(Fix errors from #qa)
  CHANGELOG.md
  Cargo.lock
  contracts/math/andromeda-curve/Cargo.toml
  contracts/math/andromeda-curve/src/contract.rs
  contracts/math/andromeda-curve/src/testing/tests.rs
Labels: backport/release/4

#767 Mdjakovic/update curve
  CHANGELOG.md
  contracts/math/andromeda-curve/src/contract.rs
  contracts/math/andromeda-curve/src/mock.rs
  contracts/math/andromeda-curve/src/testing/mock.rs
  contracts/math/andromeda-curve/src/testing/tests.rs
  packages/andromeda-math/src/curve.rs
Labels: backport/release/4

#769 chore: bump all ADOs by minor for std update
  Cargo.lock
  contracts/app/andromeda-app-contract/Cargo.toml
  contracts/data-storage/andromeda-primitive/Cargo.toml
  contracts/ecosystem/andromeda-vault/Cargo.toml
  contracts/finance/andromeda-conditional-splitter/Cargo.toml
  contracts/finance/andromeda-cross-chain-swap/Cargo.toml
  contracts/finance/andromeda-rate-limiting-withdrawals/Cargo.toml
  contracts/finance/andromeda-timelock/Cargo.toml
  contracts/finance/andromeda-validator-staking/Cargo.toml
  contracts/finance/andromeda-vesting/Cargo.toml
  contracts/fungible-tokens/andromeda-cw20-exchange/Cargo.toml
  contracts/fungible-tokens/andromeda-cw20-staking/Cargo.toml
  contracts/fungible-tokens/andromeda-cw20/Cargo.toml
  contracts/fungible-tokens/andromeda-ics20/Cargo.toml
  contracts/fungible-tokens/andromeda-lockdrop/Cargo.toml
  contracts/fungible-tokens/andromeda-merkle-airdrop/Cargo.toml
  contracts/math/andromeda-curve/Cargo.toml
  contracts/modules/andromeda-address-list/Cargo.toml
  contracts/non-fungible-tokens/andromeda-crowdfund/Cargo.toml
  contracts/non-fungible-tokens/andromeda-cw721/Cargo.toml
  contracts/non-fungible-tokens/andromeda-marketplace/Cargo.toml
  contracts/os/andromeda-economics/Cargo.toml
  contracts/os/andromeda-ibc-registry/Cargo.toml
  contracts/os/andromeda-vfs/Cargo.toml
Labels: ci: skip-changelog, ci: skip-build, backport/release/4

#770 feat: prerelease action
  .github/workflows/prerelease.yml
Labels: ci: skip-changelog

#774 feat: SignedDecimal for Distance
  CHANGELOG.md
  Cargo.lock
  contracts/math/andromeda-distance/src/contract.rs
  contracts/math/andromeda-distance/src/testing/tests.rs
  contracts/math/andromeda-graph/Cargo.toml
  packages/andromeda-math/src/distance.rs
Labels: backport/release/4

#778 Mdjakovic/update graph
  CHANGELOG.md
  Cargo.lock
  contracts/math/andromeda-graph/Cargo.toml
  contracts/math/andromeda-graph/src/contract.rs
  contracts/math/andromeda-graph/src/testing/tests.rs
  packages/andromeda-math/src/graph.rs
Labels: backport/release/4

#779 Mdjakovic/update point
  CHANGELOG.md
  Cargo.lock
  contracts/math/andromeda-graph/src/contract.rs
  contracts/math/andromeda-graph/src/testing/mock_querier.rs
  contracts/math/andromeda-point/Cargo.toml
  contracts/math/andromeda-point/src/execute.rs
  contracts/math/andromeda-point/src/testing/tests.rs
  packages/andromeda-math/src/point.rs
Labels: backport/release/4

#787 chore: versions & changelog for release 4
  CHANGELOG.md
  Cargo.lock
  contracts/math/andromeda-graph/Cargo.toml
  contracts/math/andromeda-point/Cargo.toml
Labels: ci: skip-changelog, ci: skip-build, backport/release/4

#668 feat: Start Time for Permissions
  CHANGELOG.md
  Cargo.lock
  contracts/accounts/andromeda-fixed-multisig/src/contract.rs
  contracts/app/andromeda-app-contract/src/contract.rs
  contracts/data-storage/andromeda-boolean/src/contract.rs
  contracts/data-storage/andromeda-form/src/contract.rs
  contracts/data-storage/andromeda-primitive/src/contract.rs
  contracts/data-storage/andromeda-string-storage/src/contract.rs
  contracts/ecosystem/andromeda-vault/src/contract.rs
  contracts/finance/andromeda-conditional-splitter/src/contract.rs
  contracts/finance/andromeda-cross-chain-swap/src/contract.rs
  contracts/finance/andromeda-fixed-amount-splitter/src/contract.rs
  contracts/finance/andromeda-rate-limiting-withdrawals/src/contract.rs
  contracts/finance/andromeda-splitter/src/contract.rs
  contracts/finance/andromeda-timelock/src/contract.rs
  contracts/finance/andromeda-validator-staking/src/contract.rs
  contracts/finance/andromeda-vesting/src/contract.rs
  contracts/finance/andromeda-weighted-distribution-splitter/src/contract.rs
  contracts/fungible-tokens/andromeda-cw20-exchange/src/contract.rs
  contracts/fungible-tokens/andromeda-cw20-staking/src/contract.rs
  contracts/fungible-tokens/andromeda-cw20/src/contract.rs
  contracts/fungible-tokens/andromeda-cw20/src/testing/tests.rs
  contracts/fungible-tokens/andromeda-lockdrop/src/contract.rs
  contracts/fungible-tokens/andromeda-merkle-airdrop/src/contract.rs
  contracts/math/andromeda-counter/src/contract.rs
  contracts/math/andromeda-curve/src/contract.rs
  contracts/math/andromeda-date-time/src/contract.rs
  contracts/math/andromeda-distance/src/contract.rs
  contracts/math/andromeda-graph/src/contract.rs
  contracts/math/andromeda-matrix/src/contract.rs
  contracts/math/andromeda-point/src/contract.rs
  contracts/math/andromeda-shunting/src/contract.rs
  contracts/modules/andromeda-address-list/src/contract.rs
  contracts/modules/andromeda-address-list/src/testing/tests.rs
  contracts/modules/andromeda-rates/src/contract.rs
  contracts/modules/andromeda-schema/src/contract.rs
  contracts/non-fungible-tokens/andromeda-auction/src/contract.rs
  contracts/non-fungible-tokens/andromeda-crowdfund/src/contract.rs
  contracts/non-fungible-tokens/andromeda-cw721/src/contract.rs
  contracts/non-fungible-tokens/andromeda-marketplace/src/contract.rs
  contracts/non-fungible-tokens/andromeda-marketplace/src/testing/tests.rs
  contracts/os/andromeda-adodb/src/contract.rs
  contracts/os/andromeda-economics/src/contract.rs
  contracts/os/andromeda-ibc-registry/src/contract.rs
  contracts/os/andromeda-kernel/src/contract.rs
  contracts/os/andromeda-vfs/src/contract.rs
  packages/std/Cargo.toml
  packages/std/src/ado_base/permissioning.rs
  packages/std/src/ado_contract/execute.rs
  packages/std/src/ado_contract/permissioning.rs
  packages/std/src/common/denom.rs
  tests-integration/tests/auction_app.rs
  tests-integration/tests/marketplace_app.rs
  tests-integration/tests/rates_orch.rs
  tests-integration/tests/validator_staking.rs
Labels: packages/std

#789 FEAT: Tests integration between Curve, Counter and Graph ADOs.
  Cargo.lock
  contracts/math/andromeda-graph/src/mock.rs
  tests-integration/Cargo.toml
  tests-integration/tests/curve_app.rs
  tests-integration/tests/mod.rs
Labels: ci: skip-changelog

#793 chore: weighted distribution splitter release tag
  Cargo.lock
  contracts/finance/andromeda-weighted-distribution-splitter/Cargo.toml
Labels: ci: skip-changelog, ci: skip-build

#791 feat: Username Handling in IBC Packet
  CHANGELOG.md
  Cargo.lock
  contracts/os/andromeda-kernel/Cargo.toml
  contracts/os/andromeda-kernel/src/execute.rs
  contracts/os/andromeda-kernel/src/ibc.rs
  e2e-tests/tests/kernel_orch.rs
  packages/andromeda-testing-e2e/Cargo.toml
  packages/andromeda-testing/Cargo.toml
  packages/deploy/Cargo.toml
  packages/std/Cargo.toml
  packages/std/src/ado_base/permissioning.rs
  packages/std/src/amp/messages.rs
  packages/std/src/os/aos_querier.rs
  packages/std/src/testing/mock_querier.rs
Labels: packages/std
